export const data = {
  products: [
    {
      id: "1",
      name: "Pink Polo Shirt",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      rating: 4.5,
      numReviews: 10,
      description: "high quality shirt",
    },
    {
      id: "2",
      name: "Marl Polo Shirt",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 0,
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "3",
      name: "Slim Fit Polo Shirt",
      image: "/images/p3.jpg",
      price: 25,
      countInStock: 15,
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      id: "4",
      name: "Orange Polo Shirt",
      image: "/images/p4.jpg",
      price: 65,
      countInStock: 5,
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "5",
      name: "Fit Black Shirt",
      image: "/images/p5.jpg",
      price: 95,
      countInStock: 9,
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "6",
      name: "Fit Purpal Shirt",
      image: "/images/p6.jpg",
      price: 40,
      countInStock: 12,
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "7",
      name: "Fit Black Shirt",
      image: "/images/p7.jpg",
      price: 95,
      countInStock: 9,
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "8",
      name: "Fit White Shirt",
      image: "/images/p8.jpg",
      price: 100,
      countInStock: 6,
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "9",
      name: "Fit Black Shirt",
      image: "/images/p9.jpg",
      price: 50,
      countInStock: 11,
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      id: "10",
      name: "Fit Black Shirt",
      image: "/images/p10.jpg",
      price: 30,
      countInStock: 9,
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
